<a href="https://colab.research.google.com/github/serejaspaal/colab/blob/main/colab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
vec = np.array([1,2,3])
vec.ndim

1

In [ ]:
mat = np.array([[1,2,3],[4,5,6]])
mat.ndim

2

In [ ]:
vec.shape

(3,)

In [ ]:
mat.dtype.name

'int64'

In [ ]:
mat.itemsize

8

In [ ]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [ ]:
A = np.array([1,2,3], dtype = float)
A

array([1., 2., 3.])

In [ ]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.zeros(3,)

array([0., 0., 0.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.empty((2,5))

array([[4.82159062e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 2.34832588e+251],
       [7.25045924e+169, 7.48389165e-067, 4.75796667e-090,
        7.62073323e+169, 6.82442319e-310]])

In [ ]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [ ]:
np.arange(2.5,8.7,0.9)

array([2.5, 3.4, 4.3, 5.2, 6.1, 7. , 7.9])

In [ ]:
np.linspace(2,18,16)

array([ 2.        ,  3.06666667,  4.13333333,  5.2       ,  6.26666667,
        7.33333333,  8.4       ,  9.46666667, 10.53333333, 11.6       ,
       12.66666667, 13.73333333, 14.8       , 15.86666667, 16.93333333,
       18.        ])

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.arange(8).reshape(4,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
c = np.arange(8).reshape(4,-1)
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
c.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [ ]:
a= np.arange(6).reshape(2,-1)
np.hstack((a,a**2))

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [ ]:
np.vstack((a,a**2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 0,  1,  4],
       [ 9, 16, 25]])

In [ ]:
np.concatenate((a,a**2), axis=1)

array([[ 0,  1,  2,  0,  1,  4],
       [ 3,  4,  5,  9, 16, 25]])

In [ ]:
a = np.arange(3)
np.tile(a,(2,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [ ]:
np.tile(a,(4,1))

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [ ]:
a = np.arange(9).reshape(3,3)
b = np.arange(1,10).reshape(3,3)

In [ ]:
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a+b

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [ ]:
a*1.0/b

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [ ]:
a+1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
3*a

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [ ]:
a**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
a*b

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [ ]:
a.dot(b)

array([[ 18,  21,  24],
       [ 54,  66,  78],
       [ 90, 111, 132]])

In [ ]:
np.tile(np.arange(0,40,10),(3,1)).T + np.array([0,1,2])

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [ ]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a.min()

0

In [ ]:
a.max(axis = 0)

array([6, 7, 8])

In [ ]:
a.sum(axis = 1)

array([ 3, 12, 21])

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[2:5]

array([2, 3, 4])

In [ ]:
a[3:8:2]

array([3, 5, 7])

In [ ]:
a = np.arange(81).reshape(9,-1)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [ ]:
a[2:4]

array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [ ]:
a[:,2:4]

array([[ 2,  3],
       [11, 12],
       [20, 21],
       [29, 30],
       [38, 39],
       [47, 48],
       [56, 57],
       [65, 66],
       [74, 75]])

In [ ]:
a[2:4,2:4]

array([[20, 21],
       [29, 30]])

In [ ]:
a[-1]

array([72, 73, 74, 75, 76, 77, 78, 79, 80])

In [ ]:
a=np.arange(81).reshape(9,-1)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [ ]:
a[[2,4,5],[0,1,3]]

array([18, 37, 48])

In [ ]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a[a%5!=3]

array([ 0,  1,  2,  4,  5,  6,  7,  9, 10])

In [ ]:
a[np.logical_and(a!=7,a%5!=3)]

array([ 0,  1,  2,  4,  5,  6,  9, 10])

In [ ]:
import time

a = np.random.normal(size = (1000000,))
b = np.random.normal(size = (1000000, ))

al,bl = list(a), list(b)

In [ ]:
start = time.time()
ans = 0
for i in range(len(al)):
  ans+= al[i] * bl[i]
print(time.time() - start)

0.30098485946655273


In [ ]:
start = time.time()
ans = sum([al[i]*bl[i] for i in range(1000000)])
print(time.time() - start)

0.2747635841369629


In [ ]:
start = time.time()
ans = np.sum(a*b)
print(time.time()-start)

0.01656341552734375


In [ ]:
start = time.time()
ans = a.dot(b)
print(time.time() - start)

0.0030312538146972656


In [ ]:
import pandas as pd
ms = pd.Series([5,6,7,8,9,10])
ms

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [ ]:
ms.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
ms.values

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
ms[4]

9

In [ ]:
ms2 = pd.Series([5,6,7,8,9,10], index=['a','b','c','d','e','f'])
ms2['f']

10

In [ ]:
ms2[['a','b','f']]

a     5
b     6
f    10
dtype: int64

In [ ]:
ms2[['a','b','f']] = 0
ms2

a    0
b    0
c    7
d    8
e    9
f    0
dtype: int64

In [ ]:
ms2[ms2 > 0]

c    7
d    8
e    9
dtype: int64

In [ ]:
ms2[ms2>0]*2

c    14
d    16
e    18
dtype: int64

In [ ]:
ms3 = pd.Series({"a":5,'b':6,'c':7,'d':8})
ms3

a    5
b    6
c    7
d    8
dtype: int64

In [ ]:
ms3.name = 'numbers'
ms3.index.name = 'letters'
ms3

letters
a    5
b    6
c    7
d    8
Name: numbers, dtype: int64

In [ ]:
ms3.index=['A','B','C','D']
ms3

A    5
B    6
C    7
D    8
Name: numbers, dtype: int64

In [ ]:
df = pd.DataFrame({
    'country':['Kazakhstan','Russia','Belarus','Ukraine'],
    'population':[17.04,143.5,17,1],
    'square':[2720000,17000000,200000,1]
})
df

country  population    square
0  Kazakhstan       17.04   2720000
1      Russia      143.50  17000000
2     Belarus       17.00    200000
3     Ukraine        1.00         1

In [ ]:
df['country']

0    Kazakhstan
1        Russia
2       Belarus
3       Ukraine
Name: country, dtype: object

In [ ]:
df.columns

Index(['country', 'population', 'square'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
df = pd.DataFrame({
    'country':['Kazakhstan','Russia','Belarus','Ukraine'],
    'population':[17.04,143.5,17,1],
    'square':[2720000,17000000,200000,1]
}, index = ['KZ','RU','BY','UA'])
df

country  population    square
KZ  Kazakhstan       17.04   2720000
RU      Russia      143.50  17000000
BY     Belarus       17.00    200000
UA     Ukraine        1.00         1

In [ ]:
df.index.name = 'CountryCode'
df

country  population    square
CountryCode                                  
KZ           Kazakhstan       17.04   2720000
RU               Russia      143.50  17000000
BY              Belarus       17.00    200000
UA              Ukraine        1.00         1

In [ ]:
df['country']

CountryCode
KZ    Kazakhstan
RU        Russia
BY       Belarus
UA       Ukraine
Name: country, dtype: object

In [ ]:
df.loc['KZ']

country       Kazakhstan
population         17.04
square           2720000
Name: KZ, dtype: object

In [ ]:
df.iloc[0]

country       Kazakhstan
population         17.04
square           2720000
Name: KZ, dtype: object

In [ ]:
df.loc[['KZ','RU'], 'population']

CountryCode
KZ     17.04
RU    143.50
Name: population, dtype: float64

In [ ]:
df.loc['KZ':'BY',:]

country  population    square
CountryCode                                  
KZ           Kazakhstan       17.04   2720000
RU               Russia      143.50  17000000
BY              Belarus       17.00    200000

In [ ]:
df[df.population > 10][['country','square']]

country    square
CountryCode                      
KZ           Kazakhstan   2720000
RU               Russia  17000000
BY              Belarus    200000

In [ ]:
df.reset_index()

CountryCode     country  population    square
0          KZ  Kazakhstan       17.04   2720000
1          RU      Russia      143.50  17000000
2          BY     Belarus       17.00    200000
3          UA     Ukraine        1.00         1

In [147]:
df['density'] = df['population']/df['square'] * 1000000
df

country  population    square         density
CountryCode                                                  
KZ           Kazakhstan       17.04   2720000        6.264706
RU               Russia      143.50  17000000        8.441176
BY              Belarus       17.00    200000       85.000000
UA              Ukraine        1.00         1  1000000.000000

In [148]:
df.drop(['density'], axis='columns')

country  population    square
CountryCode                                  
KZ           Kazakhstan       17.04   2720000
RU               Russia      143.50  17000000
BY              Belarus       17.00    200000
UA              Ukraine        1.00         1

In [149]:
df = df.rename(columns={'CountryCode': 'country_code'})
df

country  population    square         density
CountryCode                                                  
KZ           Kazakhstan       17.04   2720000        6.264706
RU               Russia      143.50  17000000        8.441176
BY              Belarus       17.00    200000       85.000000
UA              Ukraine        1.00         1  1000000.000000

In [155]:
tdf = pd.read_csv('titanic3.csv',sep = ';')
print(tdf.head())

   pclass  survived                                             name     sex  \
0     1.0       1.0                    Allen, Miss. Elisabeth Walton  female   
1     1.0       1.0                   Allison, Master. Hudson Trevor    male   
2     1.0       0.0                     Allison, Miss. Helen Loraine  female   
3     1.0       0.0             Allison, Mr. Hudson Joshua Creighton    male   
4     1.0       0.0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

      age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0      29    0.0    0.0   24160  211,3375       B5        S    2    NaN   
1  0,9167    1.0    2.0  113781  151,5500  C22 C26        S   11    NaN   
2       2    1.0    2.0  113781  151,5500  C22 C26        S  NaN    NaN   
3      30    1.0    2.0  113781  151,5500  C22 C26        S  NaN  135.0   
4      25    1.0    2.0  113781  151,5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis,

In [157]:
print(tdf.groupby(['sex','survived'])['home.dest'].count())

sex     survived
female  0.0          47
        1.0         241
male    0.0         351
        1.0         106
Name: home.dest, dtype: int64
